<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="joint_origin_y" value="0.063" />
    <xacro:property name="joint_origin_x" value="0.0875" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://ground_rover_description/meshes/Base_Assembly.dae"/>
            </geometry>
            <origin xyz="0 0 0.015" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="0.140 0.160 0.062" />
            </geometry>
            <origin xyz="0 0 0.006" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.40442088" />
            <origin xyz="0 0 0.015" rpy="0 0 0" />
            <inertia ixx="0.00108528" ixy="-4.682e-5" ixz="-1.062e-5" 
                    iyy="0.00092849" iyz="1.266e-5" 
                    izz="0.00185279" />
        </inertial>
    </link>

    <xacro:macro name="wheel_link" params="prefix y" >
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="package://ground_rover_description/meshes/Wheel_Copy.dae" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${y}" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.03" length="0.035" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2} 0 ${y}" />
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 ${y}" />
                <mass value="0.0616546" />
                <inertia ixx="1.528e-5" ixy="-4.039e-11" ixz="9.797e-11" 
                        iyy="2.527e-5" iyz="-2.637e-12" 
                        izz="1.528e-5" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left_back" y="0" />
    <xacro:wheel_link prefix="left_front" y="0" />
    <xacro:wheel_link prefix="right_back" y="${pi}" />
    <xacro:wheel_link prefix="right_front" y="${pi}" />


    <joint name="base_joint" type="fixed" >
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${joint_origin_x / 3.50}" rpy="0 0 0" />
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_front_wheel_link" />
        <origin xyz="${-joint_origin_x} ${joint_origin_y} 0" rpy="0 0 ${pi / 2.0}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_front_wheel_link" />
        <origin xyz="${joint_origin_x} ${joint_origin_y} 0" rpy="0 0 ${pi / 2.0}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_back_wheel_link" />
        <origin xyz="${-joint_origin_x} ${-joint_origin_y} 0" rpy="0 0 ${pi / 2.0}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_back_wheel_link" />
        <origin xyz="${joint_origin_x} ${-joint_origin_y} 0" rpy="0 0 ${pi / 2.0}" />
        <axis xyz="0 1 0" />
    </joint>
</robot>